//! Python<->Rust equivalence on the diagnostics subset (Mission 5, H36).
//!
//! Reads the fixture generated by `tools/rust/generate_diagnostics_fixture.py` and
//! checks the Rust computation reproduces the Python-computed expected values within
//! the preregistered relative tolerance (1e-9). Regenerate the fixture with that
//! script; do not hand-edit it.

use std::fs;
use std::path::PathBuf;

use itd_diagnostics::diagnostics;
use itd_field::Field2D;

fn fixture_path() -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("../../fixtures/diagnostics.txt");
    path
}

fn parse_floats(line: &str) -> Vec<f64> {
    line.split_whitespace()
        .map(|token| token.parse::<f64>().expect("float"))
        .collect()
}

fn rel_close(actual: f64, expected: f64, tol: f64) -> bool {
    (actual - expected).abs() <= tol * expected.abs().max(1.0)
}

#[test]
fn rust_matches_python_reference() {
    let text = fs::read_to_string(fixture_path()).expect("fixture present");
    let lines: Vec<&str> = text.lines().collect();
    assert!(lines.len() >= 4, "fixture has header, u, v, expected");

    let header = parse_floats(lines[0]);
    let (ny, nx, h) = (header[0] as usize, header[1] as usize, header[2]);
    let u = Field2D::new(ny, nx, parse_floats(lines[1]));
    let v = Field2D::new(ny, nx, parse_floats(lines[2]));
    let expected = parse_floats(lines[3]);

    let got = diagnostics(&u, &v, h);
    let tol = 1e-9;
    assert!(
        rel_close(got.enstrophy, expected[0], tol),
        "enstrophy {} vs {}",
        got.enstrophy,
        expected[0]
    );
    assert!(
        rel_close(got.vorticity_rms, expected[1], tol),
        "vorticity_rms {} vs {}",
        got.vorticity_rms,
        expected[1]
    );
    assert!(
        rel_close(got.localization, expected[2], tol),
        "localization {} vs {}",
        got.localization,
        expected[2]
    );
}
