//! Python<->Rust equivalence on the diagnostics subset (Mission 5 H36; Mission 6 H47).
//!
//! Reads the fixture generated by `tools/rust/generate_diagnostics_fixture.py` -- SEVEN
//! named velocity fields -- and checks the Rust computation reproduces every Python
//! expected value (enstrophy, vorticity RMS, localization, palinstrophy, vorticity
//! flatness) within the preregistered relative tolerance (1e-9). Regenerate the fixture
//! with that script; do not hand-edit it.

use std::fs;
use std::path::PathBuf;

use itd_diagnostics::diagnostics;
use itd_field::Field2D;

fn fixture_path() -> PathBuf {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("../../fixtures/diagnostics.txt");
    path
}

fn parse_floats(line: &str) -> Vec<f64> {
    line.split_whitespace()
        .map(|token| token.parse::<f64>().expect("float"))
        .collect()
}

fn rel_close(actual: f64, expected: f64, tol: f64) -> bool {
    (actual - expected).abs() <= tol * expected.abs().max(1.0)
}

const LABELS: [&str; 5] = [
    "enstrophy",
    "vorticity_rms",
    "localization",
    "palinstrophy",
    "vorticity_flatness",
];

#[test]
fn rust_matches_python_reference() {
    let text = fs::read_to_string(fixture_path()).expect("fixture present");
    let lines: Vec<&str> = text.lines().collect();
    let header: Vec<&str> = lines[0].split_whitespace().collect();
    assert_eq!(header[0], "CASES", "fixture starts with a CASES count");
    let case_count: usize = header[1].parse().expect("case count");

    let tol = 1e-9;
    let mut checked = 0usize;
    let mut index = 1usize;
    while index < lines.len() {
        let case_header: Vec<&str> = lines[index].split_whitespace().collect();
        assert_eq!(case_header[0], "CASE", "each case begins with CASE <name>");
        let name = case_header[1];
        let dims = parse_floats(lines[index + 1]);
        let (ny, nx, h) = (dims[0] as usize, dims[1] as usize, dims[2]);
        let u = Field2D::new(ny, nx, parse_floats(lines[index + 2]));
        let v = Field2D::new(ny, nx, parse_floats(lines[index + 3]));
        let expected = parse_floats(lines[index + 4]);

        let got = diagnostics(&u, &v, h).as_array();
        for k in 0..5 {
            assert!(
                rel_close(got[k], expected[k], tol),
                "case {} {}: {} vs {}",
                name,
                LABELS[k],
                got[k],
                expected[k]
            );
        }
        checked += 1;
        index += 5;
    }
    assert_eq!(checked, case_count, "checked every case in the fixture");
}
